/**
 * Content model.
 *
 * Everything the site renders and every CV generated by scripts/build-cvs.tsx is
 * derived from `profile.ts`, typed against this file. Adding a project or a new
 * bullet is a data edit, never a component edit.
 *
 * The key idea behind CV tailoring: bullets are written once and *tagged* with
 * the CV variants they belong to. A scholarship CV and a technical CV therefore
 * draw from the same verified facts and differ by selection and ordering —
 * never by inventing a stronger-sounding version of the same claim.
 */

/** The four visitor paths. */
export type VisitorMode = 'engineering' | 'research' | 'scholarship' | 'everything'

/** The four generated CV documents. */
export type CvVariant = 'technical' | 'research' | 'scholarship' | 'general'

export const VISITOR_MODES: readonly VisitorMode[] = [
  'engineering',
  'research',
  'scholarship',
  'everything',
] as const

export const CV_VARIANTS: readonly CvVariant[] = [
  'technical',
  'research',
  'scholarship',
  'general',
] as const

/** Which CV a visitor path should default to. */
export const CV_FOR_MODE: Record<VisitorMode, CvVariant> = {
  engineering: 'technical',
  research: 'research',
  scholarship: 'scholarship',
  everything: 'general',
}

/**
 * A single verified statement, tagged with the CV variants it belongs in.
 * `emphasis` is the tailoring mechanism: same fact, different audiences.
 *
 * Two conventions hold across every bullet in `profile.ts`, and both are about
 * how the finished page reads rather than about any single line.
 *
 * Tense follows the work, not the section: present for something still true
 * ("Rotate across", "Teach circuit"), past for something finished ("Operated",
 * "Wired"), present participle for a build still under way ("Developing").
 *
 * No two bullets that can print in the *same* document open with the same verb.
 * Four project entries each starting "Built a…" stacked down one column is the
 * clearest signal a reader gets that a machine assembled the page — a person
 * writing five entries hears the repetition by the third and reaches for a better
 * verb, which is usually a more specific one anyway. Note that the constraint is
 * per-variant, not global: "Applied PID control" and "Applied instrumentation"
 * coexist happily because their `emphasis` sets are disjoint and no one document
 * ever shows both. Check overlap, not the whole file.
 *
 * Bullets are also authored strongest-first within each entry, because the CV
 * generator prints only the leading few — see `cvBulletsFor` in `lib/select.ts`.
 */
export type Bullet = {
  text: string
  emphasis: CvVariant[]
}

export type Link = {
  label: string
  href: string
  /** Shown as plain text in CVs; ATS parsers handle bare URLs better than markup. */
  cvText?: string
}

export type Identity = {
  name: string
  /** Short role line. Must stay defensible — no aspirational job titles. */
  title: string
  location: string
  email: string
  /** Shown on /contact and in every generated CV document. */
  phone: string
  links: {
    github: Link
    linkedin: Link
    site: Link
  }
}

export type Education = {
  institution: string
  shortName: string
  degree: string
  field: string
  location: string
  start: string
  end: string
  expected: boolean
  coursework: string[]
  /**
   * Named `bullets` like every other tagged source, so `bulletsFor` accepts an
   * education entry directly. Currently empty: the CV states the degree, the
   * dates and the coursework, and there is no honours or GPA claim to add.
   */
  bullets: Bullet[]
}

export type Experience = {
  id: string
  role: string
  organisation: string
  location: string
  start: string
  end: string
  current: boolean
  /** One-line summary for cards and timelines. */
  summary: string
  bullets: Bullet[]
  skills: string[]
  /** Rank within each visitor path; null hides it from that path. */
  rank: Partial<Record<VisitorMode, number>>
}

export type ArchNodeKind =
  | 'sensor'
  | 'compute'
  | 'actuator'
  | 'model'
  | 'storage'
  | 'service'
  | 'ui'
  | 'output'

export type ArchNode = {
  id: string
  label: string
  kind: ArchNodeKind
  /** Concrete part number or library, where the source material states one. */
  detail?: string
  /** Grid position for the rendered block diagram. */
  col: number
  row: number
}

export type ArchEdge = {
  from: string
  to: string
  label?: string
  kind?: 'data' | 'signal' | 'control' | 'power'
}

export type Architecture = {
  caption: string
  cols: number
  rows: number
  nodes: ArchNode[]
  edges: ArchEdge[]
}

export type Decision = {
  /** The choice made. */
  choice: string
  /** The failure mode or constraint that forced it. */
  because: string
}

export type ProjectStatus = 'shipped' | 'in-progress' | 'complete' | 'ongoing'

/**
 * A photograph or screenshot belonging to a project.
 *
 * `asset` is an id in `data/media.ts`, never a raw path — that keeps alt text,
 * export widths and the confidentiality rules in one file, so an image cannot be
 * published from here without going through the manifest first.
 */
export type ProjectImage = {
  asset: string
  caption?: string
}

export type Project = {
  slug: string
  name: string
  /** One honest line. No superlatives that the source material cannot support. */
  tagline: string
  /**
   * When the work happened. Free text, but it prints beside `dates()` output in
   * the generated CVs, so it follows the same convention: an en dash with no
   * spaces around it, and a capitalised "Present". A projects column reading
   * "2026 – present" next to an experience column reading "Mar 2025–Present" is
   * the sort of thing that makes a document look assembled rather than set.
   */
  period: string
  status: ProjectStatus
  statusNote?: string
  repo?: string
  technologies: string[]
  /** Free-text domains used for filtering and the research interest graph. */
  domains: string[]
  team?: string

  // ---- Case study ----
  problem: string
  why: string
  approach: string[]
  architecture?: Architecture
  challenges: string[]
  decisions: Decision[]
  results: string[]
  learned: string[]
  images?: ProjectImage[]

  // ---- Audience adaptation ----
  /** Position within each path. Absent key = not surfaced in that path. */
  rank: Partial<Record<VisitorMode, number>>
  /** Audience-specific opening sentence for the project card. */
  framing: Partial<Record<VisitorMode, string>>
  /** Tagged bullets consumed by the CV generator. */
  bullets: Bullet[]
}

export type SkillGroup = {
  label: string
  items: string[]
  /** Which CVs list this group, and in what priority. */
  emphasis: CvVariant[]
}

export type LeadershipRole = {
  id: string
  role: string
  organisation: string
  location?: string
  start: string
  end: string
  current: boolean
  summary: string
  bullets: Bullet[]
  rank: Partial<Record<VisitorMode, number>>
}

export type Certification = {
  name: string
  issuer: string
  year: string
  emphasis: CvVariant[]
}

export type ResearchInterest = {
  id: string
  label: string
  /** What he is actually curious about, grounded in work he has done. */
  description: string
  /** Project slugs / experience ids that evidence this interest. */
  evidence: string[]
}

export type TimelineEntry = {
  year: string
  label: string
  detail: string
  kind: 'education' | 'work' | 'project' | 'service'
}

export type Profile = {
  identity: Identity
  /** Summary lines, one per CV variant. Website copy lives in page components. */
  summaries: Record<CvVariant, string>
  education: Education[]
  experience: Experience[]
  projects: Project[]
  skills: SkillGroup[]
  leadership: LeadershipRole[]
  certifications: Certification[]
  researchInterests: ResearchInterest[]
  timeline: TimelineEntry[]
}
